on:
  pull_request:
    branches:
      - main

name: Build container

env:
  CONTAINER_NAME: jordemort/plex:${{ github.event.inputs.container_tag || 'latest' }}
  PLATFORMS: linux/amd64
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  publish:
    name: Build and publish image
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to container registry
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Build and push container
        run: |
          docker pull "$CONTAINER_NAME" || true

          docker buildx build --pull \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --platform "$PLATFORMS" \
            --cache-from "$CONTAINER_NAME" \
            --tag "$CONTAINER_NAME" .

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
