name: Build container
on:
  push:
    branches:
      - main
  pull_request:

  # Allow for manually running
  workflow_dispatch:
    inputs:
      container_tag:
        description: Tag for container
        default: "latest"
        required: true

  schedule:
    - cron: '0 0 1/1 * *'

jobs:
  cibuild:
    runs-on: ubuntu-20.04
    env:
      CONTAINER_NAME: jordemort/plex
      DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
      BUILD_PLATFORMS: linux/amd64
      RAW_CONTAINER_TAG: ${{ github.event.inputs.container_tag || github.event.pull_request.head.ref || 'latest' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Needed for buildx gha cache to work
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Build container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONTAINER_TAG=$(echo "$RAW_CONTAINER_TAG" | sed 's/[^a-zA-Z0-9]\+/-/')

          docker buildx build \
            --platform "$BUILD_PLATFORMS" \
            --tag "$CONTAINER_NAME:$CONTAINER_TAG" \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --pull --push .

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
