name: Update nvidia driver to latest version
on:
  workflow_dispatch:

  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 0 * * *"

jobs:
  update_routes:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: bin/update-driver-version.sh

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Update nvidia driver to latest version"
